import { Student } from '../types';

// Sensitive fields (national id, guardian name/phone, nationality, birth date)
// are intentionally blank: they are served per role by the get-student-contacts
// Edge Function after login (security review S2). Source of truth: Supabase `students`.

export const STUDENTS_GRADE_4: Student[] = [
  // ==========================================
  // الصف الرابع الابتدائي - فصل 1 (33 طالباً)
  // ==========================================
  {
    id: 'std-4-1-01',
    studentNumber: '4101',
    name: 'أركان ابراهيم قاسم العواضي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-02',
    studentNumber: '4102',
    name: 'باسل محمد بشير عمر',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-03',
    studentNumber: '4103',
    name: 'تيم احمد محمد الرويثي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-04',
    studentNumber: '4104',
    name: 'حمد عبدالمحسن بن حمد المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-05',
    studentNumber: '4105',
    name: 'حمود أحمد نواف الكنيس',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-06',
    studentNumber: '4106',
    name: 'حمود عبدالواحد حمود حزام الشلالي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-07',
    studentNumber: '4107',
    name: 'خالد بن سلطان بن محمد العنزي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-08',
    studentNumber: '4108',
    name: 'رائد خالد سالم الحارثي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-09',
    studentNumber: '4109',
    name: 'رضا احمد خالد مستو',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-10',
    studentNumber: '4110',
    name: 'زعال عبدالمحسن زعال الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-11',
    studentNumber: '4111',
    name: 'زيد عوض خويلد العنزي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-12',
    studentNumber: '4112',
    name: 'سعد فهيد عايض العجمي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-13',
    studentNumber: '4113',
    name: 'سعيد سعود فلاح المطيري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-14',
    studentNumber: '4114',
    name: 'سليمان عبدالله سليمان ال معروف',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-15',
    studentNumber: '4115',
    name: 'صالح عادل صالح حسين',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-16',
    studentNumber: '4116',
    name: 'صالح عبدالهادي صالح المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-17',
    studentNumber: '4117',
    name: 'عبدالرحمن اسامه عبداللطيف الجعيمان',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-18',
    studentNumber: '4118',
    name: 'عبدالرحمن حاتم ابوحجل فرح',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-19',
    studentNumber: '4119',
    name: 'عبدالرحمن غدير بن حمد الغويدري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-20',
    studentNumber: '4120',
    name: 'عمر خالد بن سعد الحمل',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-21',
    studentNumber: '4121',
    name: 'عمر صالح محمد الوجيه',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-22',
    studentNumber: '4122',
    name: 'فارس محمد بن مسفر الشمراني',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-23',
    studentNumber: '4123',
    name: 'فهد سالم محمد المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-24',
    studentNumber: '4124',
    name: 'فواز بن سعيد بن علي الزويدي المهري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-25',
    studentNumber: '4125',
    name: 'كرم ماهر سعدالله العايش',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-26',
    studentNumber: '4126',
    name: 'لؤي ابراهيم أمين طاهر ناصر',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-27',
    studentNumber: '4127',
    name: 'مبارك محمد مبارك الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-28',
    studentNumber: '4128',
    name: 'محمد صالح ناصر العنسي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-29',
    studentNumber: '4129',
    name: 'محمد علي بن سالم المهري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-30',
    studentNumber: '4130',
    name: 'مهدي محمد العمياء',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-31',
    studentNumber: '4131',
    name: 'ناصر سلطان ناصر المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-32',
    studentNumber: '4132',
    name: 'ناصر عبد الله ناصر الشكرة الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-1-33',
    studentNumber: '4133',
    name: 'يزن فيصل مهيوب - احمد',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-1',
    className: 'رابع 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },

  // ==========================================
  // الصف الرابع الابتدائي - فصل 2 (33 طالباً)
  // ==========================================
  {
    id: 'std-4-2-01',
    studentNumber: '4201',
    name: 'أمير ادهم احمد خشافه',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-02',
    studentNumber: '4202',
    name: 'احمد جمال بابكر الجباره',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-03',
    studentNumber: '4203',
    name: 'تركي أحمد عبار الشمري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-04',
    studentNumber: '4204',
    name: 'جابر مسلم بن عامر الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-05',
    studentNumber: '4205',
    name: 'حازم حسن عباس - محمد مصطفى',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-06',
    studentNumber: '4206',
    name: 'حمد سلطان ناصر المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-07',
    studentNumber: '4207',
    name: 'حمد محمد احمد العجمي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-08',
    studentNumber: '4208',
    name: 'خالد هيثم محمد موسى',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-09',
    studentNumber: '4209',
    name: 'خطاب هلال محسن سالم باديان',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-10',
    studentNumber: '4210',
    name: 'راكان محمد بن علي العجمي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-11',
    studentNumber: '4211',
    name: 'ريان سلمان بن محمد السعيد',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-12',
    studentNumber: '4212',
    name: 'سالم سعد بن سالم الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-13',
    studentNumber: '4213',
    name: 'سلمان محمد ابن جمل المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-14',
    studentNumber: '4214',
    name: 'سلمان محمد دويحس المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-15',
    studentNumber: '4215',
    name: 'صالح علي بن حمد المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-16',
    studentNumber: '4216',
    name: 'عبدالرحمن شجاع فهد العرجاني',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-17',
    studentNumber: '4217',
    name: 'عبدالعزيز طارق علي الحداء',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-18',
    studentNumber: '4218',
    name: 'عبدالله مبارك بن ماجد العرجاني',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-19',
    studentNumber: '4219',
    name: 'فهد ناصر بن فهد الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-20',
    studentNumber: '4220',
    name: 'فياض فياض بن فهد العجمي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-21',
    studentNumber: '4221',
    name: 'كيان محمد احمد الفليو',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-22',
    studentNumber: '4222',
    name: 'محمد اسامه محمد عبدالرحيم',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-23',
    studentNumber: '4223',
    name: 'محمد توفيق مهيوب المجيدي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-24',
    studentNumber: '4224',
    name: 'محمد جابر بن عبدالله الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-25',
    studentNumber: '4225',
    name: 'محمد عبدالرحمن محمد المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-26',
    studentNumber: '4226',
    name: 'محمد مناع بداح الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-27',
    studentNumber: '4227',
    name: 'محمد مهدي حسين ال معجبه',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-28',
    studentNumber: '4228',
    name: 'محمد يسلم حمد المهري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-29',
    studentNumber: '4229',
    name: 'مذخر ذيب حسن ال جابر',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-30',
    studentNumber: '4230',
    name: 'منصور مدوس ابن جابر الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-31',
    studentNumber: '4231',
    name: 'موسى بلال سماح الرشيدي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-32',
    studentNumber: '4232',
    name: 'يوسف بسام - ابوعون',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-2-33',
    studentNumber: '4233',
    name: 'يوسف راشد صالح عبدالسلامه',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-2',
    className: 'رابع 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },

  // ==========================================
  // الصف الرابع الابتدائي - فصل 3 (34 طالباً)
  // ==========================================
  {
    id: 'std-4-3-01',
    studentNumber: '4301',
    name: 'الوليد احمد علي المعمري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-02',
    studentNumber: '4302',
    name: 'حزام صالح حسين العواضي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-03',
    studentNumber: '4303',
    name: 'حسام سالم محمد المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-04',
    studentNumber: '4304',
    name: 'حسن بخيت حمد القحطاني',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-05',
    studentNumber: '4305',
    name: 'حسن عبدالرحمن حسن الشطيري العرجاني',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-06',
    studentNumber: '4306',
    name: 'حمزه حسن بن حسين الشطيري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-07',
    studentNumber: '4307',
    name: 'خالد فهد بن محمد القحطاني',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-08',
    studentNumber: '4308',
    name: 'راكان محمد بن علي المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-09',
    studentNumber: '4309',
    name: 'سالم محمد سالم دغيش',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-10',
    studentNumber: '4310',
    name: 'سالم مهدي سالم العرجاني',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-11',
    studentNumber: '4311',
    name: 'سلطان جابر احمد عسيري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-12',
    studentNumber: '4312',
    name: 'شباب نايف شباب البقمي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-13',
    studentNumber: '4313',
    name: 'صالح جمال صالح علي كشميم',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-14',
    studentNumber: '4314',
    name: 'صالح ماجد عبدالله الصيعري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-15',
    studentNumber: '4315',
    name: 'عبدالرحمن احمد ناصر لدرم حدج',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-16',
    studentNumber: '4316',
    name: 'عبدالعزيز محمد مناور القحطاني',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-17',
    studentNumber: '4317',
    name: 'عبدالله مبارك عبدالله العرجاني',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-18',
    studentNumber: '4318',
    name: 'عبيد فهد سعيد الصيعري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-19',
    studentNumber: '4319',
    name: 'علي خالد علي الصيعري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-20',
    studentNumber: '4320',
    name: 'عمر معدي مفرح البقمي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-21',
    studentNumber: '4321',
    name: 'فالح جابر ناصر المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-22',
    studentNumber: '4322',
    name: 'مبارك علي بن سالم المهري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-23',
    studentNumber: '4323',
    name: 'محمد خالد علي المهري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-24',
    studentNumber: '4324',
    name: 'محمد سالم محمد المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-25',
    studentNumber: '4325',
    name: 'محمد عبدالله حمد المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-26',
    studentNumber: '4326',
    name: 'محمد فهد بن نغيمش المطيري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-27',
    studentNumber: '4327',
    name: 'مشاري سعيد بن محمد المري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-28',
    studentNumber: '4328',
    name: 'مشعل عبيد ثاري الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-29',
    studentNumber: '4329',
    name: 'مشعل مناور بن مشرع القحطاني',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-30',
    studentNumber: '4330',
    name: 'مشعل يزيد أحمد علوي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-31',
    studentNumber: '4331',
    name: 'موسى منير احمد حسن مهدي',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-32',
    studentNumber: '4332',
    name: 'ناصر سالم بداح الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-33',
    studentNumber: '4333',
    name: 'ناهض عمار ناهض الدوسري',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-4-3-34',
    studentNumber: '4334',
    name: 'وسام احمد خضران الزهراني',
    gradeLevel: 'الصف الرابع الابتدائي',
    classId: 'class-4-3',
    className: 'رابع 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  }
];
