import { Student } from '../types';

// Sensitive fields (national id, guardian name/phone, nationality, birth date)
// are intentionally blank: they are served per role by the get-student-contacts
// Edge Function after login (security review S2). Source of truth: Supabase `students`.

export const STUDENTS_GRADE_5: Student[] = [
  // ==========================================
  // الصف الخامس الابتدائي - فصل 1 (30 طالباً)
  // ==========================================
  {
    id: 'std-5-1-01',
    studentNumber: '5101',
    name: 'أحمد جابر أحمد عسيري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-02',
    studentNumber: '5102',
    name: 'أنس مروان - ابو زغنونه',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-03',
    studentNumber: '5103',
    name: 'بدر سعد بن حمدان البقمي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-04',
    studentNumber: '5104',
    name: 'حمد عوض بن صالح الجعيدري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-05',
    studentNumber: '5105',
    name: 'حمزة -ردفان - الجيلاني',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-06',
    studentNumber: '5106',
    name: 'حمود محمد بن منصور السبيعي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-07',
    studentNumber: '5107',
    name: 'راكان بلد بن سبيل الحربي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-08',
    studentNumber: '5108',
    name: 'راكان محسن بن ناصر الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-09',
    studentNumber: '5109',
    name: 'ريان مجاهد حمد الغويدري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-10',
    studentNumber: '5110',
    name: 'سراج مهدي حسين ال معجبه',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-11',
    studentNumber: '5111',
    name: 'سعود عبدالله مبارك العجمي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-12',
    studentNumber: '5112',
    name: 'سعيد بن سالم بن سعيد المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-13',
    studentNumber: '5113',
    name: 'شاجع فياض بن فهد العجمي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-14',
    studentNumber: '5114',
    name: 'طارق كمال علي بن ماضي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-15',
    studentNumber: '5115',
    name: 'عبدالكريم أحمد عبار الشمري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-16',
    studentNumber: '5116',
    name: 'عبدالله عليان بن ناصر العتيبي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-17',
    studentNumber: '5117',
    name: 'علي احمد علي الشهري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-18',
    studentNumber: '5118',
    name: 'عمران بن سعيد موحي البلوي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-19',
    studentNumber: '5119',
    name: 'فهد سالم بن فهد العجمي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-20',
    studentNumber: '5120',
    name: 'قصي ابراهيم امين طاهر ناصر',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-21',
    studentNumber: '5121',
    name: 'ماجد فخر الدين السماني عبدالمحمود',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-22',
    studentNumber: '5122',
    name: 'متعب ماجد رديف الزقروطي الشمري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-23',
    studentNumber: '5123',
    name: 'محمد غازي الشريف',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-24',
    studentNumber: '5124',
    name: 'مشاري سعد مساعد الغامدي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-25',
    studentNumber: '5125',
    name: 'ناصر بداح ناصر الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-26',
    studentNumber: '5126',
    name: 'ناصر عبدالله ناصر الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-27',
    studentNumber: '5127',
    name: 'ناصر علي ناصر المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-28',
    studentNumber: '5128',
    name: 'نايف فرج سعيد المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-29',
    studentNumber: '5129',
    name: 'هايف فيحان فالح المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-1-30',
    studentNumber: '5130',
    name: 'يوسف عثمان يوسف يحيى بابكر',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-1',
    className: 'خامس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },

  // ==========================================
  // الصف الخامس الابتدائي - فصل 2 (29 طالباً)
  // ==========================================
  {
    id: 'std-5-2-01',
    studentNumber: '5201',
    name: 'آدم عمرو محمد المالكي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-02',
    studentNumber: '5202',
    name: 'أحمد حسين بن احمد الدحيم',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-03',
    studentNumber: '5203',
    name: 'حسين ناصر بن سالم المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-04',
    studentNumber: '5204',
    name: 'حمد محمد بن حمد العجمي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-05',
    studentNumber: '5205',
    name: 'حمود احمد علي المعمري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-06',
    studentNumber: '5206',
    name: 'حمود سليمان العساف',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-07',
    studentNumber: '5207',
    name: 'خالد حمد ابن علي المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-08',
    studentNumber: '5208',
    name: 'راكان فلاح سعد القحطاني',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-09',
    studentNumber: '5209',
    name: 'زياد ناصر خميس باوهال',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-10',
    studentNumber: '5210',
    name: 'سالم تركي سالم المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-11',
    studentNumber: '5211',
    name: 'سعود سلمان بن عبدالهادي المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-12',
    studentNumber: '5212',
    name: 'شفيع حمد ابن محمد المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-13',
    studentNumber: '5213',
    name: 'طلال إيهاب زكي محلاوي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-14',
    studentNumber: '5214',
    name: 'عامر عبدالله سعد المهري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-15',
    studentNumber: '5215',
    name: 'عبدالعزيز عبدالرحمن محمد المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-16',
    studentNumber: '5216',
    name: 'عبدالله فهد بن سالم المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-17',
    studentNumber: '5217',
    name: 'عبدالله ناصر عبدالله الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-18',
    studentNumber: '5218',
    name: 'عبيد فهاد بن ناصر الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-19',
    studentNumber: '5219',
    name: 'فالح متعب فالح المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-20',
    studentNumber: '5220',
    name: 'فهد سعد بداح الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-21',
    studentNumber: '5221',
    name: 'قاسم محمد سالم عبده',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-22',
    studentNumber: '5222',
    name: 'مبارك جازع بن فهاد الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-23',
    studentNumber: '5223',
    name: 'محمد عبدالله مبارك العجمي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-24',
    studentNumber: '5224',
    name: 'محمد عمر حمد المهري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-25',
    studentNumber: '5225',
    name: 'محمد منصور مناور القحطاني',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-26',
    studentNumber: '5226',
    name: 'محمد ناجي بخيت كل',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-27',
    studentNumber: '5227',
    name: 'مهند شائع بن سعد القحطاني',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-28',
    studentNumber: '5228',
    name: 'ناصر محسن عبدالقادر ناصر العديني',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-2-29',
    studentNumber: '5229',
    name: 'ناصر مشعان بن مبارك الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-2',
    className: 'خامس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },

  // ==========================================
  // الصف الخامس الابتدائي - فصل 3 (29 طالباً)
  // ==========================================
  {
    id: 'std-5-3-01',
    studentNumber: '5301',
    name: 'أحمد يزيد أحمد علوي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-02',
    studentNumber: '5302',
    name: 'اسامه علي ضيف الله العواضي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-03',
    studentNumber: '5303',
    name: 'جارالله حمد مبارك المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-04',
    studentNumber: '5304',
    name: 'خالد عماد احمد الزهراني',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-05',
    studentNumber: '5305',
    name: 'خالد فهد خالد بوروزه',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-06',
    studentNumber: '5306',
    name: 'راشد حمد سالم المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-07',
    studentNumber: '5307',
    name: 'زيد صالح محمد الشمراني',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-08',
    studentNumber: '5308',
    name: 'سالم بن محمد بن ناصر الجربوعي المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-09',
    studentNumber: '5309',
    name: 'سالم محمد سالم المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-10',
    studentNumber: '5310',
    name: 'سعود عبدالله بن هادي الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-11',
    studentNumber: '5311',
    name: 'صالح علي بن صغير اليامي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-12',
    studentNumber: '5312',
    name: 'عامر ناهض بن عامر الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-13',
    studentNumber: '5313',
    name: 'عبدالعزيز أحمد محمد الزهراني',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-14',
    studentNumber: '5314',
    name: 'عبدالله فهيد حمد العرجاني',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-15',
    studentNumber: '5315',
    name: 'عبدالله مهدي حسين ال معجبه',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-16',
    studentNumber: '5316',
    name: 'عبدالمحسن سلطان سعود الشهراني',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-17',
    studentNumber: '5317',
    name: 'علي بدر علي المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-18',
    studentNumber: '5318',
    name: 'علي عبدالله مانع العنزي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-19',
    studentNumber: '5319',
    name: 'فراج علي فراج الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-20',
    studentNumber: '5320',
    name: 'فلاح سعود فلاح المطيري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-21',
    studentNumber: '5321',
    name: 'ماجد سعود شبيب الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-22',
    studentNumber: '5322',
    name: 'محمد سالم محمد المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-23',
    studentNumber: '5323',
    name: 'محمد مرسل بن غانم الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-24',
    studentNumber: '5324',
    name: 'محمد مسلم ناصر الشكره',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-25',
    studentNumber: '5325',
    name: 'موسى مرعي بن موسى الشهري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-26',
    studentNumber: '5326',
    name: 'ناصر حمد عامر المري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-27',
    studentNumber: '5327',
    name: 'نايف سعود بن مانع الدوسري',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-28',
    studentNumber: '5328',
    name: 'نواف نائف سليمان باست',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-5-3-29',
    studentNumber: '5329',
    name: 'يزيد سعود بن عبدالله المالكي',
    gradeLevel: 'الصف الخامس الابتدائي',
    classId: 'class-5-3',
    className: 'خامس 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  }
];
