import { Student } from '../types';

// Sensitive fields (national id, guardian name/phone, nationality, birth date)
// are intentionally blank: they are served per role by the get-student-contacts
// Edge Function after login (security review S2). Source of truth: Supabase `students`.

export const STUDENTS_GRADE_3: Student[] = [
  // ==========================================
  // الصف الثالث الابتدائي - فصل 1 (34 طالباً)
  // ==========================================
  {
    id: 'std-3-1-01',
    studentNumber: '3101',
    name: 'احمد البدري احمد البدري محمد',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-02',
    studentNumber: '3102',
    name: 'تركي ماجد ناجي الوادعي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-03',
    studentNumber: '3103',
    name: 'تميم ناصر خميس باوهال',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-04',
    studentNumber: '3104',
    name: 'ثنيان متعب بن عبدالعزيز الثنيان',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-05',
    studentNumber: '3105',
    name: 'حزام دخيل علي المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-06',
    studentNumber: '3106',
    name: 'حسان علي عايش الاهدل',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-07',
    studentNumber: '3107',
    name: 'حسين علي سالم باوهال',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-08',
    studentNumber: '3108',
    name: 'ساري مانع بن راشد المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-09',
    studentNumber: '3109',
    name: 'سعود سلطان طالب الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-10',
    studentNumber: '3110',
    name: 'سعيد انور التميمي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-11',
    studentNumber: '3111',
    name: 'صاهود محمد صاهود الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-12',
    studentNumber: '3112',
    name: 'عبدالله احمد عبدالله الدخيل',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-13',
    studentNumber: '3113',
    name: 'عبدالله محمد عبدالله النضير',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-14',
    studentNumber: '3114',
    name: 'عبدالهادي حمد عبدالهادي المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-15',
    studentNumber: '3115',
    name: 'عبدالهادي محمد مخزيم الفراط القحطاني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-16',
    studentNumber: '3116',
    name: 'علي سالم علي المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-17',
    studentNumber: '3117',
    name: 'عمر عبدالله محمد قايد الوتر',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-18',
    studentNumber: '3118',
    name: 'عيد ابراهيم بن مسفر القحطاني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-19',
    studentNumber: '3119',
    name: 'فارس احمد خميس شايع',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-20',
    studentNumber: '3120',
    name: 'فهد بدر فهد الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-21',
    studentNumber: '3121',
    name: 'فهد عبدالله فهد الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-22',
    studentNumber: '3122',
    name: 'قاسم علي سالم باوهال',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-23',
    studentNumber: '3123',
    name: 'محمد احمد محمد العواد',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-24',
    studentNumber: '3124',
    name: 'محمد حسين محمد المهري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-25',
    studentNumber: '3125',
    name: 'محمد صالح ناصر المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-26',
    studentNumber: '3126',
    name: 'محمد عبدالله سرور باوهال',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-27',
    studentNumber: '3127',
    name: 'محمد عبدالله محمد المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-28',
    studentNumber: '3128',
    name: 'محمد مسعود بن عبدالهادي المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-29',
    studentNumber: '3129',
    name: 'محمد هادي حسين ال صلاح',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-30',
    studentNumber: '3130',
    name: 'مزيد بن عبدالله بن مزيد الخالدي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-31',
    studentNumber: '3131',
    name: 'مسعد رضوان عبدالله اليافعي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-32',
    studentNumber: '3132',
    name: 'نايف ياسر سعد المطيري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-33',
    studentNumber: '3133',
    name: 'نواف ابراهيم سعيد الشهراني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-1-34',
    studentNumber: '3134',
    name: 'وسام محمد مظف الحارثي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-1',
    className: 'ثالث 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },

  // ==========================================
  // الصف الثالث الابتدائي - فصل 2 (34 طالباً)
  // ==========================================
  {
    id: 'std-3-2-01',
    studentNumber: '3201',
    name: 'بادي رفدان محمد الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-02',
    studentNumber: '3202',
    name: 'تميم منصور محمد الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-03',
    studentNumber: '3203',
    name: 'حزام مبخوت فهد الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-04',
    studentNumber: '3204',
    name: 'خالد عمر بن سالم المنهالي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-05',
    studentNumber: '3205',
    name: 'سالم محمد سالم الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-06',
    studentNumber: '3206',
    name: 'سالم ناصر سليمان الصيعري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-07',
    studentNumber: '3207',
    name: 'سعد سلطان سعد الهاجري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-08',
    studentNumber: '3208',
    name: 'سعد عبدالله سعد المهري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-09',
    studentNumber: '3209',
    name: 'سعيد فهد سعيد الشهراني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-10',
    studentNumber: '3210',
    name: 'سلطان محمد جمعه العبدالله',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-11',
    studentNumber: '3211',
    name: 'صالح سعود عويضه المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-12',
    studentNumber: '3212',
    name: 'علي دخيل علي المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-13',
    studentNumber: '3213',
    name: 'علي فهد مثيب العتيبي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-14',
    studentNumber: '3214',
    name: 'علي قايد صالح العودي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-15',
    studentNumber: '3215',
    name: 'غيث محمد حسن الغامدي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-16',
    studentNumber: '3216',
    name: 'فهد ثلاب فهد الحراجين',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-17',
    studentNumber: '3217',
    name: 'فهد ناصر فهد الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-18',
    studentNumber: '3218',
    name: 'فياض سالم بن فهد العجمي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-19',
    studentNumber: '3219',
    name: 'فيصل شماخ بن عايض العرجاني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-20',
    studentNumber: '3220',
    name: 'فيصل فهد دويحس المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-21',
    studentNumber: '3221',
    name: 'محمد حيدر محمد عيسى',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-22',
    studentNumber: '3222',
    name: 'محمد خالد بن عبدالعزيز المطلق',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-23',
    studentNumber: '3223',
    name: 'محمد عبدالهادي بن راشد المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-24',
    studentNumber: '3224',
    name: 'مسفر عامر مسفر الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-25',
    studentNumber: '3225',
    name: 'معاذ عبدالعزيز بن علي البودوخي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-26',
    studentNumber: '3226',
    name: 'مهدي محسن مهدي العرجاني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-27',
    studentNumber: '3227',
    name: 'مهدي محمد مهدي العرجاني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-28',
    studentNumber: '3228',
    name: 'ناصر بدر ناصر الهاجري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-29',
    studentNumber: '3229',
    name: 'ناصر سعيد علي المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-30',
    studentNumber: '3230',
    name: 'هادي ناهض بن عامر الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-31',
    studentNumber: '3231',
    name: 'هاشم فؤاد سلمان الفايز',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-32',
    studentNumber: '3232',
    name: 'هشام محمد العبد',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-33',
    studentNumber: '3233',
    name: 'يزن أحمد محمد الزهراني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-2-34',
    studentNumber: '3234',
    name: 'يوسف حسين احمد بشر',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-2',
    className: 'ثالث 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },

  // ==========================================
  // الصف الثالث الابتدائي - فصل 3 (34 طالباً)
  // ==========================================
  {
    id: 'std-3-3-01',
    studentNumber: '3301',
    name: 'الياس خالد صالح المخلافي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-02',
    studentNumber: '3302',
    name: 'تركي محمد عيسى الزهراني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-03',
    studentNumber: '3303',
    name: 'تيم هاني صلاح الدين عرنوس',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-04',
    studentNumber: '3304',
    name: 'حسن شافي حسن القحطاني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-05',
    studentNumber: '3305',
    name: 'حمزه مدحت عبدالله الضو',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-06',
    studentNumber: '3306',
    name: 'خالد عبدالله ملفي الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-07',
    studentNumber: '3307',
    name: 'ذاكر حسين صالح البرماني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-08',
    studentNumber: '3308',
    name: 'رائد رضوان مصلح احمد وهيب',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-09',
    studentNumber: '3309',
    name: 'سالم عبدالهادي صالح المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-10',
    studentNumber: '3310',
    name: 'سالم ناصر سالم المصعبي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-11',
    studentNumber: '3311',
    name: 'سطام محمد سرور باوهال',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-12',
    studentNumber: '3312',
    name: 'صالح سماح صالح بارميدي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-13',
    studentNumber: '3313',
    name: 'صغير علي بن صغير اليامي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-14',
    studentNumber: '3314',
    name: 'عبدالعزيز بن عبدالله بن عوض الزهراني',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-15',
    studentNumber: '3315',
    name: 'عبدالله بندر فهد الدوسري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-16',
    studentNumber: '3316',
    name: 'عبدالله بن عبدالمحسن بن حمد المري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-17',
    studentNumber: '3317',
    name: 'عبدالله مشعل احمد الخليفه',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-18',
    studentNumber: '3318',
    name: 'عبدالله ياسر فيصل الحميري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-19',
    studentNumber: '3319',
    name: 'علي محمد علي محمود محمد حميده',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-20',
    studentNumber: '3320',
    name: 'علي سالم بن عامر المهري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-21',
    studentNumber: '3321',
    name: 'علي صالح محسن زايدة',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-22',
    studentNumber: '3322',
    name: 'علي صدام علي الضباعي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-23',
    studentNumber: '3323',
    name: 'عماد موسى داحش العامري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-24',
    studentNumber: '3324',
    name: 'عمر سعيد موحي البلوي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-25',
    studentNumber: '3325',
    name: 'عمر عثمان احمد موسي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-26',
    studentNumber: '3326',
    name: 'عمر محمد علي بدوي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-27',
    studentNumber: '3327',
    name: 'فهد يسلم حمد المهري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-28',
    studentNumber: '3328',
    name: 'قصي مروان العبد ابو زغنونه',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-29',
    studentNumber: '3329',
    name: 'مبارك عامر بن سعد المهري',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-30',
    studentNumber: '3330',
    name: 'محمد بادي محمد الحراجين',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-31',
    studentNumber: '3331',
    name: 'محمد حمدان مناحي السبيعي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-32',
    studentNumber: '3332',
    name: 'محمد علي احمد الفقير',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-33',
    studentNumber: '3333',
    name: 'محمد مفرح غالب السبيعي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-3-3-34',
    studentNumber: '3334',
    name: 'مساعد محمد بن مساعد العجمي',
    gradeLevel: 'الصف الثالث الابتدائي',
    classId: 'class-3-3',
    className: 'ثالث 3',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  }
];
