import { Student } from '../types';

// Sensitive fields (national id, guardian name/phone, nationality, birth date)
// are intentionally blank: they are served per role by the get-student-contacts
// Edge Function after login (security review S2). Source of truth: Supabase `students`.

export const STUDENTS_GRADE_6: Student[] = [
  // ==========================================
  // الصف السادس الابتدائي - فصل 1 (33 طالباً)
  // ==========================================
  {
    id: 'std-6-1-01',
    studentNumber: '6101',
    name: 'تركي ابراهيم بن احمد الزويد',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-02',
    studentNumber: '6102',
    name: 'تميم سعيد عوض المالكي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-03',
    studentNumber: '6103',
    name: 'رديف ماجد رديف الزقروطي الشمري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-04',
    studentNumber: '6104',
    name: 'سالم عبدالله سالم المري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-05',
    studentNumber: '6105',
    name: 'سامر علي احمد الصلاحي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-06',
    studentNumber: '6106',
    name: 'سطام صالح ناصر الدوسري الغيثي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-07',
    studentNumber: '6107',
    name: 'سعود راشد بن سالم المري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-08',
    studentNumber: '6108',
    name: 'سعود محمد مسفر الخثعمي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-09',
    studentNumber: '6109',
    name: 'سلمان جطلي بن فهد العجمي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-10',
    studentNumber: '6110',
    name: 'سلمان حزام بن فهد الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-11',
    studentNumber: '6111',
    name: 'سليمان بن علي بن سالم المهري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-12',
    studentNumber: '6112',
    name: 'صبيح سالم فرج المري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-13',
    studentNumber: '6113',
    name: 'عبدالعزيز مبارك سليمان آل معروف',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-14',
    studentNumber: '6114',
    name: 'عبدالله محمد عبدالله الصيعري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-15',
    studentNumber: '6115',
    name: 'عبدالله ناصر بن محمد الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-16',
    studentNumber: '6116',
    name: 'علي محمد محسن الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-17',
    studentNumber: '6117',
    name: 'عمار نصر العماري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-18',
    studentNumber: '6118',
    name: 'عمر هندي بن فايز السبيعي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-19',
    studentNumber: '6119',
    name: 'فهد شجاع بن عبدالله العجمي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-20',
    studentNumber: '6120',
    name: 'فهد مرزوق فهد الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-21',
    studentNumber: '6121',
    name: 'فهد مناع بداح الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-22',
    studentNumber: '6122',
    name: 'مبارك خالد علي المهري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-23',
    studentNumber: '6123',
    name: 'محمد حسن احمد الهمداني',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-24',
    studentNumber: '6124',
    name: 'محمد عدنان غالب',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-25',
    studentNumber: '6125',
    name: 'محمد عوض محمد القحطاني',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-26',
    studentNumber: '6126',
    name: 'محمد فايز محمد الشهري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-27',
    studentNumber: '6127',
    name: 'محمد مبارك بن جابر الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-28',
    studentNumber: '6128',
    name: 'محمد مقعد طريخم السبيعي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-29',
    studentNumber: '6129',
    name: 'محمد ناصر بن حديد الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-30',
    studentNumber: '6130',
    name: 'محمد نواف بن عجمي الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-31',
    studentNumber: '6131',
    name: 'ناشي جابر ناشي الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-32',
    studentNumber: '6132',
    name: 'ناصر بن محمد بن ناصر الجربوعي المري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-1-33',
    studentNumber: '6133',
    name: 'هاشم عباس معتوق الاحمد',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-1',
    className: 'سادس 1',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },

  // ==========================================
  // الصف السادس الابتدائي - فصل 2 (33 طالباً)
  // ==========================================
  {
    id: 'std-6-2-01',
    studentNumber: '6201',
    name: 'آسر مهند الجعلي عثمان',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-02',
    studentNumber: '6202',
    name: 'أنس جارالله بن رده المالكي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-03',
    studentNumber: '6203',
    name: 'بندر فهد بن حمدان الفهاد',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-04',
    studentNumber: '6204',
    name: 'جابر مبارك حزام المري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-05',
    studentNumber: '6205',
    name: 'حمد ذي يزن سلطان القباطي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-06',
    studentNumber: '6206',
    name: 'راشد حزام عبدالهادي المري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-07',
    studentNumber: '6207',
    name: 'زايد متعب زايد السبيعي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-08',
    studentNumber: '6208',
    name: 'سالم محمد بن دويل الصيعري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-09',
    studentNumber: '6209',
    name: 'سطام متعب احمد البليهي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-10',
    studentNumber: '6210',
    name: 'سعيد سعد حريزان المنهالي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-11',
    studentNumber: '6211',
    name: 'سلطان ناصر بن حمد الدوسري الشكري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-12',
    studentNumber: '6212',
    name: 'سلمان علي سلمان المري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-13',
    studentNumber: '6213',
    name: 'عامر سالم عامر المهري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-14',
    studentNumber: '6214',
    name: 'عبدالعزيز سلطان بن مانع الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-15',
    studentNumber: '6215',
    name: 'عبدالعزيز محبوب علي الرفاعي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-16',
    studentNumber: '6216',
    name: 'عبدالله فيصل محمد المهري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-17',
    studentNumber: '6217',
    name: 'عبدالله محمد عبدالله التريكي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-18',
    studentNumber: '6218',
    name: 'عمر عبدالرحمن قرشي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-19',
    studentNumber: '6219',
    name: 'غالي عوض خويلد العنزي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-20',
    studentNumber: '6220',
    name: 'فزاع بداح ناصر الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-21',
    studentNumber: '6221',
    name: 'فيصل معدي مفرح البقمي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-22',
    studentNumber: '6222',
    name: 'محمد بخيت بن علي المري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-23',
    studentNumber: '6223',
    name: 'محمد سعد العلي العبد',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-24',
    studentNumber: '6224',
    name: 'محمد سعود عويضه المري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-25',
    studentNumber: '6225',
    name: 'محمد فهد عبدالله المطيري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-26',
    studentNumber: '6226',
    name: 'محمد ناصر بداح الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-27',
    studentNumber: '6227',
    name: 'محمد ناصر سعيد المري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-28',
    studentNumber: '6228',
    name: 'محمد ياسر نعمان عبده',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-29',
    studentNumber: '6229',
    name: 'مرسل سعد بن دعيج الحراجين',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-30',
    studentNumber: '6230',
    name: 'مسلط مسمار مسلط السبيعي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-31',
    studentNumber: '6231',
    name: 'ناجي طريف بن ناجي الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-32',
    studentNumber: '6232',
    name: 'ناصر فهاد بن ناصر الدوسري',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  },
  {
    id: 'std-6-2-33',
    studentNumber: '6233',
    name: 'ياسر عيسى رجاء العنزي',
    gradeLevel: 'الصف السادس الابتدائي',
    classId: 'class-6-2',
    className: 'سادس 2',
    nationalId: '',
    parentName: '',
    parentPhone: '',
    gender: 'male',
  }
];
