import { User } from '../types';

export const OFFICIAL_TEACHERS_LIST: User[] = [
  {
    id: 'teacher-5',
    sequenceNumber: 5,
    username: 'saleh_aldossary',
    name: 'أ. صالح مسعود حمد الدوسري',
    nationalId: '1061885511',
    phone: '0508869616',
    email: 'Hmr3131@hotmail.com',
    role: 'teacher',
    password: '',
    subject: 'دراسات إسلامية',
    assignedClassId: 'class-5-1',
    assignedClassName: 'الصف الخامس الابتدائي (1)',
    avatar: '📖'
  },
  {
    id: 'teacher-6',
    sequenceNumber: 6,
    username: 'nasser_aldossary',
    name: 'أ. ناصر باتل محمد الدوسري',
    nationalId: '1016161554',
    phone: '0504926892',
    email: 'Nasser121846@gmail.com',
    role: 'teacher',
    password: '',
    subject: 'دراسات إسلامية',
    assignedClassId: 'class-5-3',
    assignedClassName: 'الصف الخامس الابتدائي (3)',
    avatar: '🕌'
  },
  {
    id: 'teacher-7',
    sequenceNumber: 7,
    username: 'mohammed_aljahaish',
    name: 'أ. محمد فهد عائض آل جحيش',
    nationalId: '1034056687',
    phone: '0590580707',
    email: 'Abo-fahad-7676@hotmail.com',
    role: 'teacher',
    password: '',
    subject: 'دراسات إسلامية',
    assignedClassId: 'class-3-3',
    assignedClassName: 'الصف الثالث الابتدائي (3)',
    avatar: '🕌'
  },
  {
    id: 'teacher-8',
    sequenceNumber: 8,
    username: 'hamad_almarri',
    name: 'أ. حمد محمد عبيد المري',
    nationalId: '1015876749',
    phone: '0508773729',
    email: 'Bomomed17@gmail.com',
    role: 'teacher',
    password: '',
    subject: 'دراسات إسلامية',
    assignedClassId: 'class-6-1',
    assignedClassName: 'الصف السادس الابتدائي (1)',
    avatar: '📖'
  },
  {
    id: 'teacher-9',
    sequenceNumber: 9,
    username: 'abdulrahman_alquw',
    name: 'أ. عبد الرحمن محمد عبد الله القو',
    nationalId: '1059538288',
    phone: '0555933779',
    email: 'Mohym33@icloud.com',
    role: 'teacher',
    password: '',
    subject: 'لغة عربية',
    assignedClassId: 'class-5-2',
    assignedClassName: 'الصف الخامس الابتدائي (2)',
    avatar: '📚'
  },
  {
    id: 'teacher-10',
    sequenceNumber: 10,
    username: 'mohammed_almelhem',
    name: 'أ. محمد بن سلمان بن محمد الملحم',
    nationalId: '1002645479',
    phone: '0505928521',
    email: '',
    role: 'teacher',
    password: '',
    subject: 'لغة عربية',
    assignedClassId: 'class-4-2',
    assignedClassName: 'الصف الرابع الابتدائي (2)',
    avatar: '✍️'
  },
  {
    id: 'teacher-11',
    sequenceNumber: 11,
    username: 'khaled_almulla',
    name: 'أ. خالد محمد عمر الملا',
    nationalId: '1008838706',
    phone: '0549043200',
    email: 'k.m.almulla.5552@gmail.com',
    role: 'teacher',
    password: '',
    subject: 'لغة عربية',
    assignedClassId: 'class-3-1',
    assignedClassName: 'الصف الثالث الابتدائي (1)',
    avatar: '✍️'
  },
  {
    id: 'teacher-12',
    sequenceNumber: 12,
    username: 'abdulmohsen_ajmi',
    name: 'أ. عبد المحسن هادي دواس العجمي',
    nationalId: '1004394993',
    phone: '0555933433',
    email: 'lphone-4-4@hotmail.com',
    role: 'teacher',
    password: '',
    subject: 'لغة عربية',
    assignedClassId: 'class-3-1',
    assignedClassName: 'الصف الثالث الابتدائي (1)',
    avatar: '🖋️'
  },
  {
    id: 'teacher-13',
    sequenceNumber: 13,
    username: 'abdullah_alrajani',
    name: 'أ. عبد الله ماجد العرجاني',
    nationalId: '1023987314',
    phone: '0503388118',
    email: '',
    role: 'teacher',
    password: '',
    subject: 'لغة عربية',
    assignedClassId: 'class-4-3',
    assignedClassName: 'الصف الرابع الابتدائي (3)',
    avatar: '🖋️'
  },
  {
    id: 'teacher-14',
    sequenceNumber: 14,
    username: 'osama_doghan',
    name: 'أ. اسامة عبد اللطيف عبد الرحمن الدوغان',
    nationalId: '1031692708',
    phone: '0504858995',
    email: 'Osama8995@hotmail.com',
    role: 'teacher',
    password: '',
    subject: 'رياضيات',
    assignedClassId: 'class-4-2',
    assignedClassName: 'الصف الرابع الابتدائي (2)',
    avatar: '📐'
  },
  {
    id: 'teacher-15',
    sequenceNumber: 15,
    username: 'naif_jaghyman',
    name: 'أ. نايف عبد اللطيف موسى الجغيمان',
    nationalId: '1017259076',
    phone: '0544402112',
    email: '',
    role: 'teacher',
    password: '',
    subject: 'رياضيات',
    assignedClassId: 'class-4-1',
    assignedClassName: 'الصف الرابع الابتدائي (1)',
    avatar: '📐'
  },
  {
    id: 'teacher-16',
    sequenceNumber: 16,
    username: 'abdullah_alkhaldi',
    name: 'أ. عبد المحسن عبد الله طليحان الخالدي',
    nationalId: '1059405850',
    phone: '0561388331',
    email: '',
    role: 'teacher',
    password: '',
    subject: 'رياضيات',
    assignedClassId: 'class-6-2',
    assignedClassName: 'الصف السادس الابتدائي (2)',
    avatar: '📐'
  },
  {
    id: 'teacher-17',
    sequenceNumber: 17,
    username: 'ibrahim_mahboub',
    name: 'أ. ابراهيم عبد الله صالح المحبوب',
    nationalId: '1004855274',
    phone: '0504933933',
    email: 'moment99@hotmail.com',
    role: 'teacher',
    password: '',
    subject: 'علوم',
    assignedClassId: 'class-4-1',
    assignedClassName: 'الصف الرابع الابتدائي (1)',
    avatar: '🔬'
  },
  {
    id: 'teacher-18',
    sequenceNumber: 18,
    username: 'abdulaziz_khalfan',
    name: 'أ. عبد العزيز إبراهيم الخلفان',
    nationalId: '1002623120',
    phone: '0506923615',
    email: 'alzaem_2002@yahoo.com',
    role: 'teacher',
    password: '',
    subject: 'علوم',
    assignedClassId: 'class-3-2',
    assignedClassName: 'الصف الثالث الابتدائي (2)',
    avatar: '🧪'
  },
  {
    id: 'teacher-19',
    sequenceNumber: 19,
    username: 'mohammed_alhassan',
    name: 'أ. محمد أحمد محمد الحسن',
    nationalId: '1001831971',
    phone: '0568397917',
    email: '',
    role: 'teacher',
    password: '',
    subject: 'علوم',
    assignedClassId: 'class-6-1',
    assignedClassName: 'الصف السادس الابتدائي (1)',
    avatar: '🔭'
  },
  {
    id: 'teacher-20',
    sequenceNumber: 20,
    username: 'abdulrahman_aldossary',
    name: 'أ. عبد الرحمن غنام عبد الرحمن الدوسري',
    nationalId: '1008970608',
    phone: '0504853755',
    email: 'Abd.aldosry1398@gmail.com',
    role: 'teacher',
    password: '',
    subject: 'اجتماعيات',
    assignedClassId: 'class-6-2',
    assignedClassName: 'الصف السادس الابتدائي (2)',
    avatar: '🌍'
  },
  {
    id: 'teacher-23',
    sequenceNumber: 23,
    username: 'khaled_hulaibi',
    name: 'أ. خالد نجيب خالد الحليبي',
    nationalId: '1002722427',
    phone: '0503919868',
    email: '',
    role: 'teacher',
    password: '',
    subject: 'انجليزي',
    assignedClassId: 'class-3-2',
    assignedClassName: 'الصف الثالث الابتدائي (2)',
    avatar: '🔤'
  },
  {
    id: 'teacher-24',
    sequenceNumber: 24,
    username: 'khalifa_alqaemi',
    name: 'أ. خليفة سعد القعيبي',
    nationalId: '1077033494',
    phone: '0556129529',
    email: '',
    role: 'teacher',
    password: '',
    subject: 'تربية بدنية',
    assignedClassId: 'class-5-3',
    assignedClassName: 'الصف الخامس الابتدائي (3)',
    avatar: '⚽'
  },
  {
    id: 'teacher-25',
    sequenceNumber: 25,
    username: 'mohammed_malki',
    name: 'أ. محمد عمر المالكي',
    nationalId: '1063203507',
    phone: '0501212213',
    email: '',
    role: 'teacher',
    password: '',
    subject: 'حاسب الى',
    assignedClassId: 'class-5-1',
    assignedClassName: 'الصف الخامس الابتدائي (1)',
    avatar: '💻'
  },
  {
    id: 'teacher-22',
    sequenceNumber: 22,
    username: 'faihan_almarri',
    name: 'أ. فيحان المري',
    email: 'f.f.almarri@hotmail.com',
    role: 'teacher',
    password: '',
    subject: 'معلم',
    avatar: '👨‍🏫',
    phone: '0508773700'
  }
];

