// Generates the SQL INSERT statements for Sync-1 seeding, from the same
// local data modules the app ships today. Prints SQL to stdout — it does
// NOT connect to Supabase itself (no service_role key needed here). The
// output is applied via the Supabase MCP connector (execute_sql), one
// block per table, so it can be reviewed before running.
import { createHash } from 'node:crypto';
import { OFFICIAL_TEACHERS_LIST } from '../services/teachersData';
import { OFFICIAL_CLASSES_LIST } from '../services/officialClassesData';
import { OFFICIAL_STUDENTS_LIST } from '../services/officialStudentsData';
import { INITIAL_PERIODS } from '../services/initialData';
import {
  OFFICIAL_TIMETABLE_RECORDS,
  extractPeriod2AssignmentsFromTimetable,
  mapLegacyTimetableTeacherId,
  isUnmappedTimetableTeacherId
} from '../services/timetableData';

const SCHOOL_ID = 'zbt-primary';

function esc(v: string | null | undefined): string {
  if (v === null || v === undefined) return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
}
function boolLit(v: boolean | undefined): string {
  return v ? 'true' : 'false';
}
function phoneHash(phone: string | undefined): string {
  const digits = (phone || '').replace(/[^0-9]/g, '');
  return createHash('sha256').update(digits).digest('hex');
}
function nationalIdHash(id: string | undefined): string {
  if (!id) return 'NULL';
  return esc(createHash('sha256').update(id.trim()).digest('hex'));
}

const lines: string[] = [];
lines.push('-- Generated by scripts/seedSupabase.ts — review before applying.');
lines.push('BEGIN;');
lines.push('');

// --- schools ---
lines.push(`INSERT INTO schools (id, name, academic_year) VALUES`);
lines.push(`  (${esc(SCHOOL_ID)}, ${esc('مدرسة زيد بن ثابت الابتدائية')}, ${esc('1447 - 1448 هـ')});`);
lines.push('');

// --- teachers (PII hashed, never plain phone/nationalId in phone_hash column) ---
lines.push('INSERT INTO teachers (id, school_id, sequence_number, username, display_name, role, subject, assigned_class_id, avatar, phone_hash, national_id_hash, email, is_active) VALUES');
lines.push(
  OFFICIAL_TEACHERS_LIST.map(t =>
    `  (${esc(t.id)}, ${esc(SCHOOL_ID)}, ${t.sequenceNumber ?? 'NULL'}, ${esc(t.username)}, ${esc(t.name)}, ${esc(t.role)}, ${esc(t.subject)}, ${esc(t.assignedClassId)}, ${esc(t.avatar)}, ${esc(phoneHash(t.phone))}, ${nationalIdHash(t.nationalId)}, ${esc(t.email)}, true)`
  ).join(',\n') + ';'
);
lines.push('');

// --- classes ---
lines.push('INSERT INTO classes (id, school_id, name, short_name, grade_level, section, capacity, homeroom_teacher_id, academic_year) VALUES');
lines.push(
  OFFICIAL_CLASSES_LIST.map(c => {
    const section = c.id.split('-').pop() || '';
    return `  (${esc(c.id)}, ${esc(SCHOOL_ID)}, ${esc(c.name)}, ${esc((c as any).shortName || c.name)}, ${esc(c.gradeLevel)}, ${esc(section)}, ${(c as any).capacity ?? 35}, ${c.teacherId ? esc(c.teacherId) : 'NULL'}, ${esc('1447 - 1448 هـ')})`;
  }).join(',\n') + ';'
);
lines.push('');

// --- students (batched — 364 rows) ---
const STUDENT_BATCH = 100;
for (let i = 0; i < OFFICIAL_STUDENTS_LIST.length; i += STUDENT_BATCH) {
  const batch = OFFICIAL_STUDENTS_LIST.slice(i, i + STUDENT_BATCH);
  lines.push('INSERT INTO students (id, school_id, class_id, national_id, student_number, name, grade_level, class_name, parent_name, parent_phone, gender, nationality, birth_date, home_phone, chronic_condition, notes) VALUES');
  lines.push(
    batch.map(s =>
      `  (${esc(s.id)}, ${esc(SCHOOL_ID)}, ${esc(s.classId)}, ${esc(s.nationalId)}, ${esc(s.studentNumber)}, ${esc(s.name)}, ${esc(s.gradeLevel)}, ${esc(s.className)}, ${esc(s.parentName)}, ${esc(s.parentPhone)}, ${esc(s.gender)}, ${esc(s.nationality || 'سعودي')}, ${s.birthDate ? esc(s.birthDate) : 'NULL'}, ${esc(s.homePhone)}, ${boolLit(s.chronicCondition)}, ${esc(s.notes)})`
    ).join(',\n') + ';'
  );
  lines.push('');
}

// --- period_schedules ---
lines.push('INSERT INTO period_schedules (school_id, period_number, name, start_time, end_time, is_attendance_period) VALUES');
lines.push(
  INITIAL_PERIODS.map(p =>
    `  (${esc(SCHOOL_ID)}, ${p.periodNumber}, ${esc(p.name)}, ${esc(p.startTime)}, ${esc(p.endTime)}, ${boolLit(p.isAttendancePeriod)})`
  ).join(',\n') + ';'
);
lines.push('');

// --- timetable_versions (one initial published version) + timetable_entries ---
lines.push("INSERT INTO timetable_versions (id, school_id, label, status, source, published_at) VALUES");
lines.push(`  ('00000000-0000-0000-0000-000000000001', ${esc(SCHOOL_ID)}, ${esc('1447-T1-initial')}, 'published', 'migration', now());`);
lines.push('');

const dayArabicMap: Record<string, string> = {
  sunday: 'الأحد', monday: 'الإثنين', tuesday: 'الثلاثاء', wednesday: 'الأربعاء', thursday: 'الخميس'
};

const entryRows: string[] = [];
let skippedUnmapped = 0;
for (const record of OFFICIAL_TIMETABLE_RECORDS) {
  const resolvedTeacherId = mapLegacyTimetableTeacherId(record.teacherId);
  if (isUnmappedTimetableTeacherId(resolvedTeacherId)) {
    skippedUnmapped += record.entries.length;
    continue;
  }
  for (const e of record.entries) {
    entryRows.push(
      `  (${esc(SCHOOL_ID)}, ${esc(resolvedTeacherId)}, ${esc(e.classId)}, ${esc(e.day)}, ${esc(dayArabicMap[e.day] || e.dayArabic)}, ${e.periodNumber}, ${esc(e.subject)}, '00000000-0000-0000-0000-000000000001')`
    );
  }
}
const ENTRY_BATCH = 150;
for (let i = 0; i < entryRows.length; i += ENTRY_BATCH) {
  lines.push('INSERT INTO timetable_entries (school_id, teacher_id, class_id, day_of_week, day_arabic, period_number, subject, version_id) VALUES');
  lines.push(entryRows.slice(i, i + ENTRY_BATCH).join(',\n') + ';');
  lines.push('');
}
lines.push(`-- skipped ${skippedUnmapped} timetable_entries rows for unmapped legacy teacher ids (owner decision pending)`);
lines.push('');

// --- daily_period_assignments (from the same self-healing extraction the app uses) ---
const assignments = extractPeriod2AssignmentsFromTimetable();
lines.push('INSERT INTO daily_period_assignments (id, school_id, class_id, class_name, day_of_week, day_arabic, teacher_id, teacher_name, period_number, subject, notes, version_id) VALUES');
lines.push(
  assignments.map(a =>
    `  (${esc(a.id)}, ${esc(SCHOOL_ID)}, ${esc(a.classId)}, ${esc(a.className)}, ${esc(a.day)}, ${esc(a.dayArabic)}, ${esc(a.teacherId)}, ${esc(a.teacherName)}, ${a.periodNumber}, ${esc(a.subject)}, ${esc(a.notes)}, '00000000-0000-0000-0000-000000000001')`
  ).join(',\n') + ';'
);
lines.push('');

// --- school_settings ---
lines.push('INSERT INTO school_settings (school_id, settings_json) VALUES');
lines.push(`  (${esc(SCHOOL_ID)}, '{"period2StartTime":"07:45","period2EndTime":"08:30","lockAttendanceOutsidePeriod":false}'::jsonb);`);
lines.push('');

lines.push('COMMIT;');

console.log(lines.join('\n'));
console.error(`\n-- summary: ${OFFICIAL_TEACHERS_LIST.length} teachers, ${OFFICIAL_CLASSES_LIST.length} classes, ${OFFICIAL_STUDENTS_LIST.length} students, ${entryRows.length} timetable entries (${skippedUnmapped} skipped), ${assignments.length} daily period-2 assignments`);
